title: Scientific Python
baseURL: "https://scientific-python.org"
languageCode: en-us
theme: scientific-python-hugo-theme
DefaultContentLanguage: en
relativeURLs: true
disableKinds: ["term", "taxonomy"]
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

params:
  description: Community developed and owned ecosystem for scientific computing

  images:
    - /images/logo.svg

  plausible:
    dataDomain: scientific-python.org

  post_meta:
    - author
    - date

  style:
    vars:
      highlightColor: "#004811"
      menuHighlightColor: "#5ca038"

  navbarlogo:
    image: logo.svg
    altText: A green tree on a white hill at the end of a green path in the shape of the letter 'S'.
    text: Scientific Python
    link: /

  navbar:
    - title: Home
      url: /
    - title: Blog
      url: https://blog.scientific-python.org
    - title: Learn
      url: https://learn.scientific-python.org

  hero:
    # Main hero title
    title: Scientific Python
    # Hero subtitle (optional)
    subtitle: Community developed, community owned
    # Button text
    buttontext: About
    # Where the main hero button links to
    buttonlink: about
    # Hero image (from static/images/___)
    image: logo.svg

  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://github.com/scientific-python/
        icon: github
      - link: https://www.youtube.com/c/ScientificPython-org
        icon: youtube
      - link: https://fosstodon.org/@scientific_python
        icon: mastodon
      - link: https://discuss.scientific-python.org
        icon: discourse
      - link: https://discord.com/invite/vur45CbwMz
        icon: discord

    quicklinks:
      column1:
        title: ""
        links:
          - text: About
            link: /about/
          - text: Roadmap
            link: /roadmap/
          - text: Code of Conduct
            link: /code_of_conduct/
      column2:
        title: "Maintainers"
        links:
          - text: SPECs
            link: /specs/
          - text: Summits
            link: /summits/
          - text: Calendars
            link: /calendars
      column3:
        links:
          - text: Press kit
            link: /press-kit
